# Generated by Django 5.0.6 on 2025-04-03 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0003_login_last_login_login_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Login',
            new_name='Register',
        ),
    ]
