# Generated by Django 5.0.6 on 2025-04-04 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0005_alter_employee_eid'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='qr_codes/'),
        ),
    ]
