# Generated by Django 5.0.6 on 2025-04-06 04:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0008_company_employee_company'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='company',
        ),
        migrations.DeleteModel(
            name='Company',
        ),
    ]
